//! Generated gateway bootstrap for sdkwork-iam.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router() -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_iam_app_api::gateway_mount().await);
    router = router.merge(sdkwork_routes_iam_backend_api::gateway_mount());
    router = router.merge(sdkwork_routes_iam_open_api::gateway_mount().await);
    ApplicationAssembly { router }
}
