//! Generated gateway bootstrap for sdkwork-iam.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use std::sync::Arc;

use axum::Router;
use sdkwork_web_bootstrap::{
    assemble_multi_surface_router, PgPoolReadinessCheck, ServiceRouterConfig, SqliteReadinessCheck,
};

pub struct ApplicationAssembly {
    pub router: Router,
}

async fn service_router_config() -> ServiceRouterConfig {
    match sdkwork_iam_database_host::bootstrap_iam_database_from_env().await {
        Ok(host) => {
            if let Some(pool) = host.pool().as_postgres() {
                return ServiceRouterConfig::default()
                    .with_readiness_check(Arc::new(PgPoolReadinessCheck::new(pool.clone())));
            }
            if let Some(pool) = host.pool().as_sqlite() {
                return ServiceRouterConfig::default()
                    .with_readiness_check(Arc::new(SqliteReadinessCheck::new(pool.clone())));
            }
        }
        Err(_) => {}
    }

    ServiceRouterConfig::default().with_always_ready()
}

pub async fn assemble_application_router() -> ApplicationAssembly {
    let config = service_router_config().await;
    let app = sdkwork_routes_iam_app_api::gateway_mount().await;
    let backend = sdkwork_routes_iam_backend_api::gateway_mount();
    let open = sdkwork_routes_iam_open_api::gateway_mount().await;

    let router = assemble_multi_surface_router([app, backend, open], config);

    ApplicationAssembly { router }
}
