//! Generated API assembly bootstrap for sdkwork-iam.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router() -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_iam_app_api::gateway_mount().await);
    router = router.merge(sdkwork_routes_iam_backend_api::gateway_mount().await);
    router = router.merge(sdkwork_routes_iam_open_api::gateway_mount().await);
    ApiAssembly { router }
}
