use sdkwork_web_contract::{HttpMethod, HttpRoute};
use sdkwork_web_core::HttpRouteManifest;

const IAM_APP_API_ROUTES: &[HttpRoute] = &[
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions",
        "auth",
        "sessions.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions/login_context_selection",
        "auth",
        "sessions.loginContextSelection.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions/organization_selection",
        "auth",
        "sessions.organizationSelection.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/auth/sessions/current",
        "auth",
        "sessions.current.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/auth/sessions/current",
        "auth",
        "sessions.current.update",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/auth/sessions/current",
        "auth",
        "sessions.current.delete",
    ),
    HttpRoute::refresh_token(
        HttpMethod::Post,
        "/app/v3/api/auth/sessions/refresh",
        "auth",
        "sessions.refresh",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/password_reset_requests",
        "auth",
        "passwordResetRequests.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/password_resets",
        "auth",
        "passwordResets.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/auth/registrations",
        "auth",
        "registrations.create",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/oauth/providers",
        "oauth",
        "oauth.providers.list",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/authorization_urls",
        "oauth",
        "oauth.authorizationUrls.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations",
        "oauth",
        "oauth.deviceAuthorizations.create",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}",
        "oauth",
        "oauth.deviceAuthorizations.retrieve",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/scans",
        "oauth",
        "oauth.deviceAuthorizations.scans.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/password_completions",
        "oauth",
        "oauth.deviceAuthorizations.passwordCompletions.create",
    ),
    HttpRoute::public(
        HttpMethod::Post,
        "/app/v3/api/oauth/device_authorizations/{deviceAuthorizationId}/session_exchanges",
        "oauth",
        "oauth.deviceAuthorizations.sessionExchanges.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Get,
        "/app/v3/api/oauth/callbacks/{providerCode}",
        "oauth",
        "oauth.callbacks.retrieve",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/callbacks/{providerCode}",
        "oauth",
        "oauth.callbacks.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/mini_program_sessions",
        "oauth",
        "oauth.miniProgramSessions.create",
    ),
    HttpRoute::credential_entry_bootstrap(
        HttpMethod::Post,
        "/app/v3/api/oauth/sessions",
        "oauth",
        "oauth.sessions.create",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/oauth/account_links",
        "oauth",
        "oauth.accountLinks.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/oauth/account_links/{accountLinkId}",
        "oauth",
        "oauth.accountLinks.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/oauth/grants",
        "oauth",
        "oauth.grants.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/oauth/grants/{grantId}",
        "oauth",
        "oauth.grants.delete",
    ),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/oauth/authorizations/{authorizationStateId}/completions",
        "oauth",
        "oauth.authorizations.completions.create",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/system/iam/runtime",
        "system",
        "iam.runtime.retrieve",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/system/iam/verification_policy",
        "system",
        "iam.verificationPolicy.retrieve",
    ),
    HttpRoute::public(
        HttpMethod::Get,
        "/app/v3/api/system/iam/account_binding_policy",
        "system",
        "iam.accountBindingPolicy.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/users/current",
        "iam",
        "users.current.retrieve",
    )
    .with_required_permission("iam:self"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/iam/users/current",
        "iam",
        "users.current.update",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Patch,
        "/app/v3/api/iam/users/current/password",
        "iam",
        "users.current.password.update",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/iam/users/current/email_bindings",
        "iam",
        "users.current.emailBindings.create",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/iam/users/current/email_bindings",
        "iam",
        "users.current.emailBindings.delete",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Post,
        "/app/v3/api/iam/users/current/phone_bindings",
        "iam",
        "users.current.phoneBindings.create",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Delete,
        "/app/v3/api/iam/users/current/phone_bindings",
        "iam",
        "users.current.phoneBindings.delete",
    )
    .with_required_permission("iam.profile.update"),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/organizations",
        "iam",
        "organizations.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/organizations/tree",
        "iam",
        "organizations.tree.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/organization_memberships",
        "iam",
        "organizationMemberships.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/departments",
        "iam",
        "departments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/departments/tree",
        "iam",
        "departments.tree.retrieve",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/department_assignments",
        "iam",
        "departmentAssignments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/positions",
        "iam",
        "positions.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/position_assignments",
        "iam",
        "positionAssignments.list",
    ),
    HttpRoute::dual_token(
        HttpMethod::Get,
        "/app/v3/api/iam/role_bindings",
        "iam",
        "roleBindings.list",
    ),
];

/// IAM operations that intentionally accept no framework credential.
pub const IAM_ANONYMOUS_OPERATION_IDS: &[&str] = &[
    "oauth.providers.list",
    "oauth.deviceAuthorizations.retrieve",
    "oauth.deviceAuthorizations.scans.create",
    "oauth.deviceAuthorizations.sessionExchanges.create",
    "iam.runtime.retrieve",
    "iam.verificationPolicy.retrieve",
    "iam.accountBindingPolicy.retrieve",
];

/// Session routes resolved by the framework before handler execution.
pub const IAM_FRAMEWORK_SESSION_OPERATION_IDS: &[&str] = &[
    "sessions.current.retrieve",
    "sessions.current.update",
    "sessions.current.delete",
];

/// Credential-entry routes aligned with `SDKWORK_IAM_API_ROUTES` `forbidCredentialHeaders`.
pub const IAM_CREDENTIAL_ENTRY_OPERATION_IDS: &[&str] = &[
    "sessions.create",
    "sessions.loginContextSelection.create",
    "sessions.organizationSelection.create",
    "passwordResetRequests.create",
    "passwordResets.create",
    "registrations.create",
    "oauth.authorizationUrls.create",
    "oauth.deviceAuthorizations.create",
    "oauth.deviceAuthorizations.passwordCompletions.create",
    "oauth.callbacks.retrieve",
    "oauth.callbacks.create",
    "oauth.miniProgramSessions.create",
    "oauth.sessions.create",
];

pub fn app_routes() -> Vec<HttpRoute> {
    IAM_APP_API_ROUTES.to_vec()
}

pub fn iam_app_api_route_manifest() -> HttpRouteManifest {
    HttpRouteManifest::new(IAM_APP_API_ROUTES)
}

pub fn sdkwork_iam_app_api_routes() -> Vec<HttpRoute> {
    app_routes()
}
